name: pvtppr-gen
base: core18 # the base snap is the execution environment for this snap
version: '3.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Generate digital documents to be stored without servers
description: |
  PvtPpr Generator will let you generate your own digital documents stored
  using LMZA+Base64 into a link format. Built ontop of ittybitty protocol.
  Make online articles, become a publisher or much more with this
  PvtPpr Generator.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil nodejs
